version: "3.9"

services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/users/1"]
      interval: 10s
      timeout: 5s
      retries: 3

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "8002:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/products/1"]
      interval: 10s
      timeout: 5s
      retries: 3